#! /bin/bash

WORKING_DIR="$HOME/.songs"
TARGET_PLAYER='mpv'
export PYTHONIOENCODING='utf-8'

if [ ! -d $WORKING_DIR ]; then
	mkdir $WORKING_DIR
fi

show_queue_help(){
	echo "play   -   plays all songs in queue list"
	echo "add    -   adds song in queue list"
	echo "clear  -   clears all songs in queue"
	echo "show   -   displays all songs in queue"
	echo "exit   -   close queue cli"
}

add_song_queue(){
SONG_STRING=$@
	echo "adding $SONG_STRING to queue..."
	echo $SONG_STRING >> $WORKING_DIR/queue_list
	echo "added to queue. Check with show command."
}

display_queue(){
	line_no=0
	QUEUE_FILE=$WORKING_DIR/queue_list
	while IFS= read -r line; do
		line_no=$((line_no+1))
		echo "$line_no - $line"
	done < $QUEUE_FILE
	echo -e "\nto remove type remove <number_of_line>"
}

start_queue_cli(){
	QUEUE_BASH=false
	while [ $QUEUE_BASH != "true" ]; do
		read -p "youtube-cli> " CMD
		case $CMD in
			"help"|"h")
				show_queue_help
				;;
			"show")
				display_queue
				;;
			"remove"*)
				LINE_NUMBER=${CMD:5}
				remove_queue_line $LINE_NUMBER
				;;
			"add"*)
				SONG_STRING=${CMD:4}
				add_song_queue $SONG_STRING
				;;
			"exit"|"EXIT")
				QUEUE_BASH=true
				;;
			*)
				echo "Seems invalid command type help for more."
				;;
		esac
	done
}

show_help(){
	echo -e "Usage: youtube-cli [option] [argument]\n"
	echo "-p/--play <title> - search and play audio of the first YouTube search result for <title>."
	echo "-i/--info - view saved songs and the amount of space they take."
}

inv_par(){
	echo "invalid parameters. use the flag --help to get available parameters."
}

play_song(){
	arg="$@"
	echo "search: $arg"
	link="$(python3 `which ytcli` --query "$arg")"
        file=$(echo "$link" | sed 's/.*=//')
        info="$(python3 `which ytcli` --info "$link")"
        echo -e $info && echo
        info="`echo $info | head -1`"
        if [ -f "$WORKING_DIR/$file" ]; then
                mpv $WORKING_DIR/$file
        else
                echo -e "${info%%Uploader: *}\t|\t\033[0;32m$file" >> $HOME/.songs/saved
                youtube-dl -f 251 --audio-format "aac" -o - "$link" | tee "$file" | $TARGET_PLAYER -
        fi
}

cd $WORKING_DIR

case "$#" in
	"0")
		show_help
		;;

	"1")
		case "$1" in
			'-h'|'--help')
				show_help
			;;

			'-i'|'--info')
				cat $HOME/.songs/saved
				du -hs $WORKING_DIR
			;;

			'-q'|'--queue'|'queue')
				start_queue_cli
			;;
		esac
		;;

	"2")
		case "$1" in
			'-p'|'--play')
				play_song "$2"
			;;
		esac
		;;

	*)
		if [ "$1" = "-p" ] || [ "$1" = "--play" ]; then
			play_song "${@:2}"
		else
			inv_par
		fi
		;;
esac
